### ISSUE TITLE
Register กรอกภาษาไทยไม่ได้

### ISSUE THREAD

**Issue by mameaw14** [kritsana-chaikaew/human-for-hire#12]

**Comment by kaisukez** [comment]
กรอกช่องไหนไม่ได้

https://imgur.com/a/WGME4
https://imgur.com/a/z8ruJ

**Comment by kaisukez** [comment]
https://imgur.com/a/WGME4

**Comment by mameaw14** [comment]
หน้าสมัครสมาชิกอ่ะ
https://imgur.com/glegQsm
https://imgur.com/R3nRpbd
