### ISSUE TITLE
Project Structure && Name Convention

### ISSUE THREAD

**Issue by kanoonsantikul** [kritsana-chaikaew/human-for-hire#26]
**Folder Structure**
ใน template ของบางแอพจะใช้ templates/appname/... แต่บางแอพใช้ templates/...

- hello/templates/hello/...
- post/templates/...
- signupLogin/templates/...
- userprofile/templates/userprofile/...

`result = หาบักนานมาก`

**CamelCase**
app `signupLogin` 
app `userprofile`

**View**
มี app hello ใช้ generic view อยู่ app เดียว

**Comment by mameaw14** [comment]
### Naming Convention
ref. PEP 8 https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles

**App names (Package and Module Names)** - all-lowercase names. underscores can be used.
**Class names** - CapitalizedWords 
**Function Names** - lower_case_with_underscores

**Comment by mameaw14** [comment]
แก้แล้ว ที่  commit  b53381996a0c87b311e9ae5afdeaa0810e658174
